on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust-toolchain: [stable]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: clippy, rustfmt
          override: true
      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version
      - name: Cache build artifacts
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}
      - name: Compile and release
        uses: avitex/rust-release.action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          binary: mdbook-tera
